cc_library(
  name = "stats",
  srcs = [
    "stats.cc",
  ],
  hdrs = [
    "stats.h",
  ],
    deps = [
    "@nlohmann_json//:json",
  ],
  visibility = [
    "//:__subpackages__",
  ],
)

# Create cc_binary